# using ~/.pgpass to store user/password
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: jobspageio_app_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: jobspageio_app_test
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: jobspageio_app_prod
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  host: ec2-23-23-244-144.compute-1.amazonaws.com
  database: d3i9q8usgbbssg
  user: flfvhezyolxhjr
  #password: Figaro.env.database_password
  password: XiDsVDSpPK0VQvguts_oBlyhFW
  pool: 5
  timeout: 5000
